### PR TITLE
Feat/thomas  user dom

### PR DESCRIPTION
**Pull request by thomedpete**
Neccesary checkmarks:

    [x] All Tests are Passing

    [x] The code will run locally

Type of change

    [x] New feature
    [] Bug Fix

Implements/Fixes:

This adds the on load function to create a random user and display said users name 

Check the correct boxes

    [x] This broke nothing
    [] This broke some stuff
    [] This broke everything

Testing Changes

    [x] No Tests have been changed
    [] Some Tests have been changed
    [] All of the Tests have been changed(Please describe what in the world happened)

Checklist:

    [] My code has no unused/commented out code
    [] I have reviewed my code
    [] I have commented my code, particularly in hard-to-understand areas
    [] I have fully tested my code

### CODE REVIEW

**Review by justenanderson-commits — APPROVED** [review]
I think this all looks good. I'm guessing we'll remove that testUsersArray once we connect to the API, yeah?

**Review by justenanderson-commits — APPROVED** [review]
This looks like it'll work! Love the tab icon. I'm guessing we'll remove the testUsersArray once we connect to the API, right?

**Comment by thomedpete** [comment]
I have resolved the conflicts, however It should still get a second set of eyes on it.

**Comment by thomedpete** [comment]
> 

Yes it goes away when the fetch comes.

**Pull request merged**
